# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-19 09:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('message', ckeditor.fields.RichTextField(max_length=1000, verbose_name='内容')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_name', models.CharField(max_length=20, verbose_name='联系人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '用户意见',
                'verbose_name_plural': '用户意见箱',
            },
        ),
    ]
