# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-19 16:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('Mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='收件人邮箱')),
                ('sent_by', models.CharField(max_length=50, null=True, verbose_name='后台发件邮箱')),
                ('template_slug', models.CharField(max_length=30, verbose_name='邮件模板')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='邮件标题')),
                ('body', models.TextField(max_length=255, null=True, verbose_name='正文数据')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
            ],
            options={
                'verbose_name_plural': '邮件发送记录',
                'verbose_name': '邮件发送记录',
            },
        ),
        migrations.CreateModel(
            name='MailServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '邮件服务商',
                'verbose_name': '邮件服务商',
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='模板名')),
                ('title', models.CharField(max_length=100, verbose_name='邮件标题')),
                ('body', ckeditor.fields.RichTextField(max_length=5000, verbose_name='邮件正文')),
                ('to_user', models.BooleanField(default=False, verbose_name='用户通知邮件')),
                ('to_admin', models.BooleanField(default=False, verbose_name='后台管理邮件')),
                ('is_html', models.BooleanField(default=True, verbose_name='是html格式')),
                ('slug', models.CharField(max_length=20, null=True, unique=True, verbose_name='模板索引slug')),
                ('receieve_groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='抄送到组')),
            ],
            options={
                'verbose_name_plural': '邮件模板',
                'verbose_name': '邮件模板',
            },
        ),
        migrations.CreateModel(
            name='MailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='昵称')),
                ('email_address', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('password', models.CharField(max_length=50, verbose_name='秘钥')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mail.MailServiceProvider', verbose_name='服务商')),
            ],
            options={
                'verbose_name_plural': '后台发信邮箱',
                'verbose_name': '后台发信邮箱',
            },
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mail.MailUser', verbose_name='后台发信邮箱'),
        ),
    ]
