# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0003_auto_20170420_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserviceprovider',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
